#! /bin/sh

full=$(realpath $1)

if [ ! -f "$full" ]; then
    echo "please run on a file"
    exit 1
fi

dir=$(echo "$full" | sed -r 's/^(.*\/)[^\/]*$/\1/') 

while true; do
    ls "$dir" | grep -P -m1 "^bld$"
    if [ $? -eq 0 ]; then # Found
        echo "${dir}bld"
        exit 0
    fi
    ls "$dir" | grep -F 'compile_commands.json' > /dev/null
    if [ $? -eq 0 -o "${dir}" = '/' ]; then
        exit 1
    fi
    dir=$(echo "${dir}" | sed -r 's|^(.*/)[^/]+/|\1|')
done
